services:
  - type: web
    name: criminal-recognition
    env: docker
    plan: free
    autoDeploy: true
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DJANGO_DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DB_PATH
        value: "/data/db.sqlite3"
    healthCheckPath: "/"
